services:
  nextjs-standalone:
    image: ghcr.io/valeriiminiailo/gha-snowball:latest
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped