services:
  nextjs-standalone:
    build:
      context: .
      dockerfile: Dockerfile
    image: gha-snowball-image
    container_name: gha-snowball-container
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
